name: Main CI
on:
  pull_request:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: liberica
        java-package: jdk+fx
        cache: maven

    - name: Build and test Balanpy
      run: |
        mvn --batch-mode --update-snapshots verify

    - uses: actions/upload-artifact@v3
      with:
        name: Balanpy
        path: target/*.jar
